### ISSUE TITLE
The question of sound

### ISSUE THREAD

**Issue by JanNeuendorf** [JanNeuendorf/SVC16#6]
Before the specifications are finalized, there is one important question left to answer. 

> Is it okay,that this system will never have sound?

I wanted to write out my thoughts on this, just in case someone sees this and wants to discuss it. 

The big argument for having no sound output is of course simplicity. 
Every emulator can output no sound correctly. 

For someone writing stuff for the system, sound adds an additional layer of complexity while arguably not offering much of  learning opportunity. At least not in the same way as drawing to a screen does. 

But having no sound is a big sacrifice so it must be considered carefully. 

If one wanted to add sound, what would be the possible ways to do this while changing the system as little as possible?
Two constrains I would have here are:
- No real changes to the instruction set. (But we can assign meaning to an unused argument.)
- No communication between the virtual computer and the system emulating it should be required in between frames. 

The second point is a big deal for sound. The sound that is played could only be updated every frame. What could this sound be? 

### Idea1 A simple beep
It could just be a beeping sound that could be triggered with the **sync** instruction. Maybe there could be a list of levels like: beep, warning, loud warning etc. and it is left to the implementation what that means.  

### Idea2 Fixed Waves
There could be a list of frequencies of sine- or square-waves that can be activated. This would require some format to be invented. It might be very difficult to fit this into a single u16.

### Idea3 A buffer for Sound 
There could be a buffer for the raw amplitude of the sound that is played every frame. 
There are a bunch of problems with this:
- One of the nice things about the system is that screen and memory are the size of the address space. I would not want to give that up. So a sound buffer would be as large as the screen, which is way to big. 
- A sound curve oscillates around zero and there is no native format for negative numbers (or floats).
- The system  is probably not fast enough to generate a sine wave.

**Comment by xyloflake** [comment]
@JanNeuendorf I'll give this some thought and then I'll comment my opinion. Initially, I would say it's okay to not have sound for a virtual computer that was built for simplicity. This however falls off when you try to create something complex like an interactive game which needs sound.

**Comment by mdoege** [comment]
Games without sound quickly get boring IMHO, so I think adding sound to SVC16 is important if you want people to create games for it.

**Idea 4**: You could stay with the 16-bit theme for the machine and let it play 16-bit mono samples from its RAM. Looking into rectavoider.svc16, it seems there is still plenty of free space in the image for a few short samples. Of course sample rate should be kept pretty low, e.g. 8,000 Hz.

If you would add a sound instruction, e.g.

  Sound sample address, sample length, halftone shift

you could even make simple tracker-style music using a single instrument sample by playing it faster or slower like on the Commodore Amiga.

Square waves sound harsh and would need to be low-pass filtered and sine waves sound very soft and dull. And I think pure waves would be a bad fit for a machine with 16-bit graphics and a fast CPU; samples are more in line with the general idea of this machine I think.

**Edit:** For the third sound parameter, you could use it to represent four values:
4 bits: # of halftone shifts upwards
4 bits: panning (left to right), e.g. 0=center, 1 to 7 pan to right, 8 to 15 pan to left
4 bits: volume
4 bits: number of sample repeats, with 0 for infinite repeats (i.e. until the next sample plays)

**Comment by xyloflake** [comment]
> Games without sound quickly get boring IMHO, so I think adding sound to SVC16 is important if you want people to create games for it.

Correct.

> If you would add a sound instruction, e.g.
>
>   Sound sample address, sample length, halftone shift

Constraint 1 states - no changes to the existing instruction set. So new instructions must NOT be introduced. The instruction set had been designed to have exactly 16 instductions.

> Square waves sound harsh and would need to be low-pass filtered and sine waves sound very soft and dull. And I think pure waves would be a bad fit for a machine with 16-bit graphics and a fast CPU; samples are more in line with the general idea of this machine I think.

I absolutely agree on this.

> **Edit:** For the third sound parameter, you could use it to represent four values:
> 4 bits: # of halftone shifts upwards
> 4 bits: panning (left to right), e.g. 0=center, 1 to 7 pan to right, 8 to 15 pan to left
> 4 bits: volume
> 4 bits: number of sample repeats, with 0 for infinite repeats (i.e. until the next sample plays)

Again, no new instructions in the instruction set. Jan has stated multiple times that he is not at all open to changing the current architecture.

**Comment by xyloflake** [comment]
I have thought about this a lot and ran some calculations to support my opinion.

I am gonna say that either don't have sound or have a sound buffer that's 2^16 16 bit values long.

For a 44.1 kHz, 16-bit, 40 ms, stereo audio buffer:

Sample rate: 44.1 kHz
Bit depth: 16-bit
Buffer duration: 40 ms
Number of channels: Stereo (2 channels)

Calculating the buffer size:

Number of samples: 44.1 kHz × 0.04 s = 1764 samples
Sample size: 16-bit × 2 channels = 4 bytes/sample
Buffer size: 1764 samples × 4 bytes/sample = 7056 bytes ~ 56k bits

This really approaches the limits of 65536 bits and I think it's fine to have a buffer that big.

However I'm not sure how you'd control sound activities like play/pause/stop without a new instruction. Any ideas?

As for the second constraint, I'd suggest extending the Sync function to be called with arg1 = 1 or something similar to denote changes to the audio and basically refresh the sound playing based on that.

I still have this as a vague idea and I'm pretty sure I haven't described the whole thing in as much detail as possible but that's a 10000 foot high level overview.

**Comment by xyloflake** [comment]
One approach to actions like play/pause/stop would be to leave it to the programmer. You can empty the buffer when you pause and reload the buffer when you play from the exact point where we paused.

The other 2 problems though, I have no idea how to solve. Especially considering not having signed integers.

**Comment by JanNeuendorf** [comment]
@mdoege 
I think that **if** you want to play a buffered sample the separate buffer **would** better than doing it from memory. That is just cleaner. 
@xyloflake 
Stereo might be very overkill. 
I think that you would not have to have play and pause instructions. It would suffice to either have the last argument of sync start a sample, that you then can not stop. Or alternatively, that is stopped when you play a new sample.

I agree that the buffer should have 2**16 elements. At 44100 samples and a u16 as one sample, this means 1.5 seconds of audio could be dispatched at once. 

The issues are:
- we would have to agree on the format 
- the samples don't fit into memory

**Comment by xyloflake** [comment]
> @xyloflake 
> Stereo might be very overkill.

Right, I just used this for calculations.

> I think that you would not have to have play and pause instructions. It would suffice to either have the last argument of sync start a sample, that you then can not stop. Or alternatively, that is stopped when you play a new sample.

Good idea, I agree.

> I agree that the buffer should have 2**16 elements. At 44100 samples and a u16 as one sample, this means 1.5 seconds of audio could be dispatched at once. 
> 
> The issues are:
> - we would have to agree on the format 

Not sure what you mean by this. Who's "we"? You currently own the software and have rights to make decisions yourself :)

If you're asking for my opinion, I think I've made it already clear.

> - the samples don't fit into memory

Valid point. This also has been my concern. Maybe lower the audio quality to support for data? Instead of having 128kbps audio, have 8 or 16kbps audio? Now that would obviously sound choppy but for a basic 16 bit computer game, I think it's enough. Another concern is with - as stated above - signed integers representing waves.

**Comment by JanNeuendorf** [comment]
> Who's "we"?

Yes, sorry weird wording. What I mean is that there would have to be a clearly specified way of representing the audio and that is really complicated. I feel like I would just write a guide on how to convert a normal audio format into the format used here that people would need to follow and then I would write a converter back into a format that the emulator can play. I am not sure that this is fun or interesting for either side. But maybe it can be made very simple. I have been looking at the **rodio** library to play sounds and they allow u16 samples by just doing:
```rust 
    fn to_f32(self) -> f32 {
        // Convert u16 to f32 in the range [-1.0, 1.0]
        (self as f32 - 32768.0) / 32768.0
    }
```
This is very easy to explain and I do not have to implement it since the library already does that. 

> Instead of having 128kbps audio, have 8 or 16kbps audio?

Yes, a lower sample rate would help. Instead of just having the last argument of **sync** be a switch to dispatch the sample, it could be a the length of the sample (with 0 meaning no sample is started). Then you can use shorter samples that don't play that long. 
This does not leave a cheap way to switch between different samples, but that is probably an interesting constrained to work around. The same goes for only one sample playing at a time.

**Comment by JanNeuendorf** [comment]
I have started a branch and started implementing this to see, if it would work. I did not update the document yet, but the changes are indicated  the Readme. I added a demo where you can use the left and right mouse buttons to play a sound.

**Comment by xyloflake** [comment]
> Yes, sorry weird wording. What I mean is that there would have to be a clearly specified way of representing the audio and that is really complicated. I feel like I would just write a guide on how to convert a normal audio format into the format used here that people would need to follow and then I would write a converter back into a format that the emulator can play. I am not sure that this is fun or interesting for either side. But maybe it can be made very simple. I have been looking at the **rodio** library to play sounds and they allow u16 samples by just doing:
> ```rust 
>     fn to_f32(self) -> f32 {
>         // Convert u16 to f32 in the range [-1.0, 1.0]
>         (self as f32 - 32768.0) / 32768.0
>     }
> ```
> This is very easy to explain and I do not have to implement it since the library already does that. 

I should mention that rodio is a fantastic audio library and I've used rodio multiple times while working @muffonlabs

Although I've had to jump to Symphonia here and there but rodio is still a very good lib. I am also not against having a different type of audio specification for svc16. We could explore potential size optimization opportunities so end programmers don't have to worry about that. This obviously doesn't mean there would be "magic" happening. They are supposed to implement the audio encoder themselves and we explain why exactly some of the choices were made. This way they don't have to brainstorm much while having potential knowledge of how all this works under the hood.

> Yes, a lower sample rate would help. Instead of just having the last argument of **sync** be a switch to dispatch the sample, it could be a the length of the sample (with 0 meaning no sample is started). Then you can use shorter samples that don't play that long. 

Is it possible to have variable sample rate? I suggest we store the intended sample rate in the first 16 bit memory chunk. This would allows programmers to have variable sample rate ranging from 0 to 65536. We obviously leave this to the programmer to "dial" the sample rate according to needs.

> This does not leave a cheap way to switch between different samples, but that is probably an interesting constrained to work around. The same goes for only one sample playing at a time. 

Right.

**Comment by xyloflake** [comment]
> I have started a branch and started implementing this to see, if it would work. I did not update the document yet, but the changes are indicated  the Readme. I added a demo where you can use the left and right mouse buttons to play a sound.   

Cool, will check out soon!

**Comment by JanNeuendorf** [comment]
> Is it possible to have variable sample rate? I suggest we store the intended sample rate in the first 16 bit memory chunk. This would allows programmers to have variable sample rate ranging from 0 to 65536. We obviously leave this to the programmer to "dial" the sample rate according to needs.

This would be possible, but I can easily play samples at a rate of 16k/x by writing each sample to the buffer x times in a row, right? 


> I am also not against having a different type of audio specification for svc16.

I am happy to hear your ideas, but honestly I can not think of anything simpler than adding 32768 to the desired value. But I would write in the specs that there is no guarantee that the system will do the interpretation as a float in a reproducible way. 
Ignoring the representation of the numbers, I think there might be programs that let you write a wav-file with u16s in this way at 16khz. So you would only need to pack the numbers correctly to get a file you can include.  

Apart from how the samples are encoded, there is another benefit to having a second buffer that is not drawn to screen. It can be used for other things. The values need to be copied one by one with the print and read instructions, but this might be worth it. If I do not want to use sound, I could decompress sprites into the sound-buffer and copy them to the screen. Having this as a hack for people to discover is kind of neat.

**Comment by xyloflake** [comment]
> This would be possible, but I can easily play samples at a rate of 16k/x by writing each sample to the buffer x times in a row, right? 

Correct, hadn't thought about that.

> I am happy to hear your ideas, but honestly I can not think of anything simpler than adding 32768 to the desired value.

I can't immediately think of it either. Do you think if we use this as an intial specification for 1.0, we can change it later on in case we find a better method? I don't think optimization ideas strike that fast so this should be given time.
 
> Ignoring the representation of the numbers, I think there might be programs that let you write a wav-file with u16s in this way at 16khz. So you would only need to pack the numbers correctly to get a file you can include.  

Correct, I agree. The main goal would be to use a program that could be used with any programming language so that people making their own emulators aren't limited by their programming language. A cli based program would be nice as you can spawn child processes from nearly all of the programming languages.

> Apart from how the samples are encoded, there is another benefit to having a second buffer that is not drawn to screen. It can be used for other things. The values need to be copied one by one with the print and read instructions, but this might be worth it. If I do not want to use sound, I could decompress sprites into the sound-buffer and copy them to the screen. Having this as a hack for people to discover is kind of neat. 

I have actually considered this from the very beginning. My whole point was to have a utility buffer. Do you think we can denote this buffer as a general purpose buffer and leave it to the programmer what they want to use it for? They only use Sync with unique arguments to actually play the sound and otherwise they can treat it as an utility buffer and decide what they want to do with it.

**Comment by JanNeuendorf** [comment]
> Correct, I agree. The main goal would be to use a program that could be used with any programming language so that people making their own emulators aren't limited by their programming language. A cli based program would be nice as you can spawn child processes from nearly all of the programming languages.

So you mean that you fear that this will be hard to implement if one wants to build an emulator in a different language? 
I can not really think of a language with which I can display the image buffer but it is impossible to play a soundwave. 
It just has to be made clear that there are no guarantees that the audio is updated on the same frame etc. 

> A cli based program would be nice as you can spawn child processes from nearly all of the programming languages.

I get what you mean here, but having to start the official cli-program that then starts some daemon to control the current sound and then passing the audio buffer over the cli .... that's a very complicated way to play a sound. 

> I have actually considered this from the very beginning. My whole point was to have a utility buffer. Do you think we can denote this buffer as a general purpose buffer and leave it to the programmer what they want to use it for? They only use Sync with unique arguments to actually play the sound and otherwise they can treat it as an utility buffer and decide what they want to do with it.

I think that this is a very good idea. 
The way you describe it is basically the way it is now in the *sound_experiment* branch. As long as you only use the **sync** instruction with `@arg3=0`, the sound is never played and you can use it as a utility buffer. 
The question is one of wording: Is it a sound-buffer that can be used for other things, or is it a utility buffer that can be used for sound? 

If it is the second option, this could be framed as "Interfacing with an extension card" instead of integrated sound. 
We could then just have the interface in the 1.0 version and it could be used for a "soundcard" or something else later. 


I also really dislike the fact that in order to sync without accidentally playing a sound, you have to set a value to zero and then use its address in the instruction. It just seems a bit inelegant.

**Comment by xyloflake** [comment]
> So you mean that you fear that this will be hard to implement if one wants to build an emulator in a different language? I can not really think of a language with which I can display the image buffer but it is impossible to play a soundwave. It just has to be made clear that there are no guarantees that the audio is updated on the same frame etc.
> 
> I get what you mean here, but having to start the official cli-program that then starts some daemon to control the current sound and then passing the audio buffer over the cli .... that's a very complicated way to play a sound.
> 

Sorry, there's been a misunderstanding. I mean to say
- the sound buffer has audio data encoded in a ***possibly*** custom specification
- the custom specification like you stated above might be generated by existing programs as a wav file as stated
  > I think there might be programs that let you write a wav-file with u16s in this way at 16khz. So you would only need to pack the numbers correctly to get a file you can include.
- I was talking about this program being usable across different languages so that different languages could be used to encode the audio data into the svc16 binary. If we used a program that was written in rust, the encoding would be limited to rust. Instead, a common cli tool that can encode the data might deem to be useful as CLI based programs can be used across almost all programming languages support child processes - thereby enabling programmer to encode using same tool with programming language of their choice.
- I do not mean to say that the official cli-program starts a daemon to control the current sound and passing audio buffer to the cli. The cli only gets involved in encoding of data in a format the emulator is able to make sense of.

> The question is one of wording: Is it a sound-buffer that can be used for other things, or is it a utility buffer that can be used for sound?
> If it is the second option, this could be framed as "Interfacing with an extension card" instead of integrated sound. We could then just have the interface in the 1.0 version and it could be used for a "soundcard" or something else later.

I am going to completely lean on the second option as it open up a wide range of possibilities without limiting the usage. It also wouldn't be very a very "hack-y" method to use the buffer for purposes beyond using it as a sound buffer.

Do you think it's possible to allow extensions to the svc16 emulator at runtime by providing some flag to let programmers create their own interface devices? (Just exploring a possibility.) For example, is it possible to allow extensions to the svc16 emulator to let programmers implement this whole sound thing we've been exploring?

> I also really dislike the fact that in order to sync without accidentally playing a sound, you have to set a value to zero and then use its address in the instruction. It just seems a bit inelegant.

I do not get what you mean by this one. You'd either execute
```
Sync 0 0 0
``` 
for frame buffer and
```
Sync 0 0 1
```
for general utility buffer to be used as sound buffer? Or am I wrong?

**Comment by JanNeuendorf** [comment]
> I am going to completely lean on the second option as it open up a wide range of possibilities without limiting the usage. It also wouldn't be very a very "hack-y" method to use the buffer for purposes beyond using it as a sound buffer

Okay, so then I will make a new branch to  work on the expansion port and buffer Ideas and the sound could later be done with that.

> Do you think it's possible to allow extensions to the svc16 emulator at runtime by providing some flag to let programmers create their own interface devices? (Just exploring a possibility.)


I guess that could be possible with something like web-assembly but that might not make much sense for things like playing sound. 

> I do not get what you mean by this one. You'd either execute...

The way I had it on the sound branch was that `@arg3` gives the length of the sound that is played. But for the expansion card idea, I would make it a simple boolean.

**Comment by xyloflake** [comment]
@JanNeuendorf I am unable to test the sound experiment branch as I am encountering this error during compilation
```bash
error: failed to run custom build command for `asio-sys v0.2.2`

Caused by:
  process didn't exit successfully: `C:\Users\Xylo\Documents\SVC16\target\release\build\asio-sys-0d98fd75b92d0db1\build-script-build` (exit code: 101)
  --- stdout
  cargo:rerun-if-env-changed=CPAL_ASIO_DIR
  CPAL_ASIO_DIR is set at C:\Users\Xylo\AppData\Local\Temp\asio_sdk
  cargo:rerun-if-changed=C:\Users\Xylo\AppData\Local\Temp\asio_sdk
  cargo:rustc-link-lib=dylib=ole32
  cargo:rustc-link-lib=dylib=User32
  cargo:rustc-link-search=C:\Users\Xylo\Documents\SVC16\target\release\build\asio-sys-895c2cb2e19007ec\out
  cargo:rustc-link-lib=static=asio
  cargo:rustc-cfg=asio

  --- stderr
  thread 'main' panicked at C:\Users\Xylo\.cargo\registry\src\index.crates.io-6f17d22bba15001f\bindgen-0.69.5\lib.rs:622:31:
  Unable to find libclang: "the `libclang` shared library at C:\\msys64\\mingw64\\bin\\libclang.dll could not be opened: LoadLibraryExW failed"
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
warning: build failed, waiting for other jobs to finish...
```

This is obviously some sort of problem with my system I'll have to take a look into but just wanted to report back.

**Comment by JanNeuendorf** [comment]
You maybe have to install libasound2-dev or some equivalent for your system?

Oh wait are you on wsl?

**Comment by xyloflake** [comment]
> You maybe have to install libasound2-dev or some equivalent for your system?
> 
> Oh wait are you on wsl?

Uh no I am purely in windows for work with school 😅

I usually use arch linux on an old laptop but it's pretty slow so I rarely use it for rust based projects 🙂

I will figure this out when I have time. The problem is at the path pointed, the libclang.dll is present. Cargo however, somehow can't detect it.

**Comment by JanNeuendorf** [comment]
Since I will probably not merge this sound experiment anyway, it is also not super important. 

But does everything else work on windows?

**Comment by xyloflake** [comment]
> Since I will probably not merge this sound experiment anyway, it is also not super important. 
> 
> But does everything else work on windows?

Yes, everything else works as expected!
